title: "Kaustubh Amritkar"
author: "Kaustubh Amritkar"
# description: "University of Wisconsin-Madison"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "publications.html", title: "Publications"}
  - {file: "cv.html", title: "CV"}
  # - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:kaustubh.amritkar@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/kaustubh-amritkar"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/kaustubh-amritkar/"}
  - {title: Google Scholar, icon: google scholar, url: "https://scholar.google.com/citations?user=qvAYURAAAAAJ&hl=en&oi=ao"}
  # - {title: Orcid, icon: orcid, url: "https://orcid.org/my-orcid?orcid=0009-0000-5270-3451"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
