title: "Trent Laack"
author: "Trent Laack"
# description: "Welcome to the Blog, I do what I want."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "publications.html", title: "Publications"}
  - {file: "cv.html", title: "CV"}
  # - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:trentonlaack@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/tlaack"}
  - {title: Linkedin, icon: linkedin, url: "www.linkedin.com/in/trenton-laack-5649062a0/"}
  # - {title: Orcid, icon: orcid, url: "https://orcid.org/my-orcid?orcid=0009-0000-5270-3451"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
